use_frameworks!
platform :ios, '12.0'

target 'PhotoBrowserKit_Example' do
  pod 'PhotoBrowserKit', :path => '../'

  target 'PhotoBrowserKit_Tests' do
    inherit! :search_paths
		pod 'SDWebImage'
  end
end
